# Generated by Django 4.0 on 2021-12-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('rock', 'Rock'), ('folk', 'Folk'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hiphop', 'Hiphop'), ('pop', 'Pop'), ('metal', 'Metal'), ('country', 'Country'), ('blues', 'Blues'), ('trad', 'Trad'), ('soul', 'Soul'), ('electronic', 'Electronic')], default='rock', max_length=50),
        ),
    ]
